financeiro/urls.py
from django.contrib import admin
from django.urls import path, include
from website import urls as website_urls
from transactions import urls as transactions_urls
from monetary import urls as monetary_urls


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(website_urls)),
    path("transactions/", include(transactions_urls)),
    path("monetary/", include(monetary_urls)),
]

transactions/urls.py
from django.urls import path
from transactions.views import (
    index_transactions,
    add_category,
    add_company,
    add_payment,
    add_registry,
    add_registry_itens,
    view_registry_itens,
)


urlpatterns = [
    path(
        "",
        index_transactions,
        name="index_transactions",
    ),
    path(
        "add_category",
        add_category,
        name="add_category",
    ),
    path(
        "add_company",
        add_company,
        name="add_company",
    ),
    path(
        "add_payment",
        add_payment,
        name="add_payment",
    ),
    path(
        "add_registry",
        add_registry,
        name="add_registry",
    ),
    path(
        "add_registry_itens",
        add_registry_itens,
        name="add_registry_itens",
    ),
    path(
        "view_registry_itens",
        view_registry_itens,
        name="view_registry_itens",
    ),
]

website/urls.py
from django.urls import path
from website.views import (index_website,)


urlpatterns = [
    path("", index_website, name="index_website",),

]

transactions/models.py
""" Define the structure of stored data """

from django.db import models
from monetary.models import Accounts


class Companies(models.Model):
    """
        Save companies names
    Attributes:
        name:

    """

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30)

    class Meta:  # pylint: disable=R0903
        """Sorted by name field"""

        db_table = "companies"
        ordering = ["name"]

    def save(self, *args, **kwargs):
        self.name = self.name.upper()

        super().save(*args, **kwargs)

    def __str__(self):
        """String for representing the ModelName object"""
        return str(self.name)

    objects = models.Manager()


class Categories(models.Model):
    """
        Save category description
    Attributes:
        description:

    """

    id = models.AutoField(primary_key=True)
    description = models.CharField(max_length=30)

    class Meta:  # pylint: disable=R0903
        """String for representing the ModelName object"""

        db_table = "categories"
        ordering = ["description"]

    def __str__(self):
        """Sorted by name field"""
        return str(self.description)

    def save(self, *args, **kwargs):
        self.description = self.description.upper()

        super().save(*args, **kwargs)

    objects = models.Manager()


class Registries(models.Model):
    """
        Saves registry of incoming and outgoing movements
    Attributes:
        favored:
        obs:

    """

    id = models.AutoField(primary_key=True)
    date = models.DateField()
    companies = models.ForeignKey(Companies, on_delete=models.CASCADE)
    category_n1 = models.ForeignKey(
        Categories, related_name="category_n1", on_delete=models.CASCADE
    )
    category_n2 = models.ForeignKey(
        Categories, related_name="category_n2", on_delete=models.CASCADE
    )
    category_n3 = models.ForeignKey(
        Categories, related_name="category_n3", on_delete=models.CASCADE
    )
    value = models.DecimalField(max_digits=10, decimal_places=2)
    in_out = models.BooleanField(default=False)
    ordering = models.IntegerField(default=0)
    obs = models.TextField(max_length=120, blank=True)

    class Meta:  # pylint: disable=R0903
        """Sorted by name field"""

        db_table = "transactions_registries"
        ordering = ["-date", "-ordering"]

    def __str__(self):
        """String for representing the ModelName object"""
        return str(f"{self.companies} - {self.id}")

    def save(self, *args, **kwargs):
        self.obs = self.obs.upper()

        super().save(*args, **kwargs)

    objects = models.Manager()


class RegistryItens(models.Model):
    """
        Saves items from registries
    Attributes:
        description:

    """

    id = models.AutoField(primary_key=True)
    description = models.CharField(max_length=30)
    brand = models.CharField(max_length=20, null=True, blank=True)
    amount = models.DecimalField(max_digits=8, decimal_places=3)
    unitary = models.DecimalField(max_digits=10, decimal_places=2)
    favored = models.CharField(max_length=20, null=True)
    registry = models.ForeignKey(Registries, on_delete=models.CASCADE)

    class Meta:  # pylint: disable=R0903
        """Sorted by name field"""

        db_table = "transactions_itens"
        ordering = ["description"]

    def __str__(self):
        """String for representing the ModelName object"""
        return str(f"{self.description} - {self.registry}")

    def save(self, *args, **kwargs):
        self.description = self.description.upper()

        super().save(*args, **kwargs)

    objects = models.Manager()


class Payments(models.Model):
    """
    Saves payments from registries
    """

    id = models.AutoField(primary_key=True)
    registry = models.ForeignKey(Registries(), on_delete=models.CASCADE)
    date = models.DateField()

    class Meta:  # pylint: disable=R0903
        """Sorted by name field"""

        db_table = "transactions_payments"
        ordering = ["date", "registry"]

    def __str__(self):
        """String for representing the ModelName object"""
        return str(self.registry)

    objects = models.Manager()


class Methods(models.Model):
    """
    Saves methods payments
    """

    id = models.AutoField(primary_key=True)
    payment = models.ForeignKey(Payments, on_delete=models.CASCADE)
    account = models.ForeignKey(Accounts, on_delete=models.CASCADE)
    value = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:  # pylint: disable=R0903
        """Sorted by name field"""

        db_table = "transactions_methods"
        ordering = ["payment"]

    def __str__(self):
        """String for representing the ModelName object"""
        return str(f"{self.account} - {self.payment}")

    objects = models.Manager()

transactions/forms.py
import datetime
from django import forms
from transactions import models


class DateInput(forms.DateInput):
    input_type = "date"


class PaymentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["date"].initial = datetime.date.today()

    class Meta:
        model = models.Payments
        fields = "__all__"
        widgets = {
            "date": DateInput(
                format="%Y-%m-%d", attrs={"class": "form-control text-center"}
            )
        }


class RegistriesForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["date"].initial = datetime.date.today()
        self.fields["value"].initial = "0.00"

    class Meta:
        companies = models.Companies.objects.all()
        categories = models.Categories.objects.all()
        model = models.Registries
        fields = "__all__"
        widgets = {
            "date": DateInput(
                format="%Y-%m-%d", attrs={"class": "form-control text-center"}
            ),
            "companies": forms.Select(
                attrs={"class": "form-control"},
                choices=[(item.id, item.name) for item in companies],
            ),
            "category_n1": forms.Select(
                attrs={"class": "form-control"},
                choices=[(item.id, item.description) for item in categories],
            ),
            "category_n2": forms.Select(
                attrs={"class": "form-control"},
                choices=[(item.id, item.description) for item in categories],
            ),
            "category_n3": forms.Select(
                attrs={"class": "form-control"},
                choices=[(item.id, item.description) for item in categories],
            ),
            "value": forms.NumberInput(
                attrs={"class": "form-control text-right"}
            ),
            "in_out": forms.Select(
                attrs={"class": "form-control text-center"},
                choices=[("DÉBITO", "DÉBITO"), ("CRÉDITO", "CRÉDITO")],
            ),
            "ordering": forms.NumberInput(
                attrs={"class": "form-control text-right"}
            ),
            "obs": forms.Textarea(
                attrs={"class": "form-control textarea", "rows": "3"}
            ),
        }


class RegistryItensForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = models.RegistryItens
        fields = "__all__"
        widgets = {
            "description": forms.TextInput(attrs={"class": "form-control"}),
            "brand": forms.TextInput(attrs={"class": "form-control"}),
            "amount": forms.NumberInput(attrs={"class": "form-control"}),
            "unitary": forms.NumberInput(attrs={"class": "form-control"}),
            "favored": forms.TextInput(attrs={"class": "form-control"}),
        }


class CompanyForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = models.Companies
        fields = "__all__"
        widgets = {"name": forms.TextInput(attrs={"class": "form-control"})}


class CategoryForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = models.Categories
        fields = "__all__"
        widgets = {
            "description": forms.TextInput(attrs={"class": "form-control"})
        }

transactions/views.py
from django.shortcuts import render
from transactions import facade as tf
from website import facade as wf


def index_transactions(request):
    month_year = request.GET.get("date")
    if month_year is None:
        month, year = wf.today_month_year()
        month_year = f"{month}/{year}"
    context = {}
    context.update(
        tf.create_registries_context_period_paid_methods_unique(month_year)
    )
    context.update(
        tf.create_category_n1_context_period_payd_methods(month_year)
    )
    context.update(
        tf.create_category_n2_context_period_payd_methods_in(month_year)
    )
    context.update(
        tf.create_category_n2_context_period_payd_methods_out(month_year)
    )
    context.update(
        tf.create_category_n3_context_period_payd_methods_in(month_year)
    )
    context.update(
        tf.create_category_n3_context_period_payd_methods_out(month_year)
    )
    context.update(tf.create_registries_context_unpayd())
    return render(request, "transactions/index_transactions.html", context)


def add_registry(request):
    if request.method == "GET":
        data = tf.form_regitries(request)
    else:
        tf.save_registry(request)
        context = tf.create_registries_context_unpayd()
        data = tf.create_registries_data_unpaid(request, context)
    return data


def add_registry_itens(request):
    if request.method == "GET":
        print(request.GET)
        data = tf.form_registry_itens(request)
    else:
        tf.save_reguistry_item(request)
        context = tf.create_registry_itens_context(
            request.POST.get("registry_id")
        )
        data = tf.create_registry_itens_data(request, context)
        print(request.POST)
    return data


def add_payment(request):
    if request.method == "GET":
        if tf.consult_payment(request.GET.get("id_selected")):
            print("OK")
        else:
            print(request.GET)
            data = tf.form_payment(request)
    else:
        tf.save_payment(request)
        print(request.POST)
    return data


def view_registry_itens(request):
    context = tf.create_registry_itens_context(request.GET.get("registry_id"))
    data = tf.create_registry_itens_data(request, context)
    return data


def add_company(request):
    if request.method == "GET":
        data = tf.form_companies(request)
    else:
        tf.save_company(request)
        data = tf.create_company_data_message(request)
    return data


def add_category(request):
    if request.method == "GET":
        data = tf.form_categories(request)
    else:
        tf.save_category(request)
        data = tf.create_category_data_message(request)
    return data

transactions/templates/transactions/card_category_n1.html
{% load humanize %}
<!-- Header -->
<div class="card-header">
	<div class="div-flex">
		<i class="icofont-check i-button-null pad-left"></i>
		<div class="div-form-control">
		</div>
		<i class="icofont-simple-up i-button pad-right"></i>
	</div>
</div>
<!-- Body -->
<div class="card-body body-vales-colaborador">
	{% for cat in category_n1 %}
	<div class="card-body-item">
		<div class="input-group">
			<div class="input-group-addon addon-my-color">
				<i class="i-button-null">{{ forloop.counter|stringformat:"02d" }}</i>
			</div>
		<div class="div-flex div-form-control">
			<div class="tamanho-70 text-left">
				<span>{{ cat.category }}</span>
			</div>
			<div class="tamanho-30 text-right color-red">
				<span>R$ {{ cat.value|floatformat:2|intcomma }}</span>
			</div>
		</div>
		<div class="input-group-addon addon-my-color">
			<i class="icofont-eye-alt i-button"
			title=""></i>
		</div>
	</div>
</div>
{% endfor %}
</div>
<!-- Footer -->
<div class="card-footer">
	<div class="div-flex">
		<div class="div-form-control div-flex">
			<div class="tamanho-80 text-left">
				<span class="font-menor"></span>
			</div>
			<div class="tamanho-20 text-right">
				<span class="font-menor"></span>
			</div>
		</div>
	</div>
</div>

transactions/templates/transactions/card_category_n2_in.html
<!-- Header -->
<div class="card-header">
	<div class="div-flex">
		<i class="icofont-check i-button-null pad-left"></i>
		<div class="div-form-control">
		</div>
		<i class="icofont-simple-up i-button pad-right"></i>
	</div>
</div>
<!-- Body -->
<div class="card-body body-vales-colaborador">
	{% for cat in category_n2_in %}
	<div class="card-body-item">
		<div class="input-group">
			<div class="input-group-addon addon-my-color">
				<i class="i-button-null">{{ forloop.counter|stringformat:"02d" }}</i>
			</div>
		<div class="div-flex div-form-control">
			<div class="tamanho-70 text-left">
				<span>{{ cat.category }}</span>
			</div>
			<div class="tamanho-30 text-right color-red">
				<span>R$ {{ cat.value }}</span>
			</div>
		</div>
		<div class="input-group-addon addon-my-color">
			<i class="icofont-eye-alt i-button"
			title=""></i>
		</div>
	</div>
</div>
{% endfor %}
</div>
<!-- Footer -->
<div class="card-footer">
	<div class="div-flex">
		<div class="div-form-control div-flex">
			<div class="tamanho-80 text-left">
				<span class="font-menor"></span>
			</div>
			<div class="tamanho-20 text-right">
				<span class="font-menor"></span>
			</div>
		</div>
	</div>
</div>

transactions/templates/transactions/card_category_n2_out.html
<!-- Header -->
<div class="card-header">
	<div class="div-flex">
		<i class="icofont-check i-button-null pad-left"></i>
		<div class="div-form-control">
		</div>
		<i class="icofont-simple-up i-button pad-right"></i>
	</div>
</div>
<!-- Body -->
<div class="card-body body-vales-colaborador">
	{% for cat in category_n2_out %}
	<div class="card-body-item">
		<div class="input-group">
			<div class="input-group-addon addon-my-color">
				<i class="i-button-null">{{ forloop.counter|stringformat:"02d" }}</i>
			</div>
		<div class="div-flex div-form-control">
			<div class="tamanho-70 text-left">
				<span>{{ cat.category }}</span>
			</div>
			<div class="tamanho-30 text-right color-red">
				<span>R$ {{ cat.value }}</span>
			</div>
		</div>
		<div class="input-group-addon addon-my-color">
			<i class="icofont-eye-alt i-button"
			title=""></i>
		</div>
	</div>
</div>
{% endfor %}
</div>
<!-- Footer -->
<div class="card-footer">
	<div class="div-flex">
		<div class="div-form-control div-flex">
			<div class="tamanho-80 text-left">
				<span class="font-menor"></span>
			</div>
			<div class="tamanho-20 text-right">
				<span class="font-menor"></span>
			</div>
		</div>
	</div>
</div>

transactions/templates/transactions/card_category_n3_in.html
<!-- Header -->
<div class="card-header">
	<div class="div-flex">
		<i class="icofont-check i-button-null pad-left"></i>
		<div class="div-form-control">
		</div>
		<i class="icofont-simple-up i-button pad-right"></i>
	</div>
</div>
<!-- Body -->
<div class="card-body body-vales-colaborador">
	{% for cat in category_n3_in %}
	<div class="card-body-item">
		<div class="input-group">
			<div class="input-group-addon addon-my-color">
				<i class="i-button-null">{{ forloop.counter|stringformat:"02d" }}</i>
			</div>
		<div class="div-flex div-form-control">
			<div class="tamanho-70 text-left">
				<span>{{ cat.category }}</span>
			</div>
			<div class="tamanho-30 text-right color-red">
				<span>R$ {{ cat.value }}</span>
			</div>
		</div>
		<div class="input-group-addon addon-my-color">
			<i class="icofont-eye-alt i-button"
			title=""></i>
		</div>
	</div>
</div>
{% endfor %}
</div>
<!-- Footer -->
<div class="card-footer">
	<div class="div-flex">
		<div class="div-form-control div-flex">
			<div class="tamanho-80 text-left">
				<span class="font-menor"></span>
			</div>
			<div class="tamanho-20 text-right">
				<span class="font-menor"></span>
			</div>
		</div>
	</div>
</div>

transactions/templates/transactions/card_category_n3_out.html
<!-- Header -->
<div class="card-header">
	<div class="div-flex">
		<i class="icofont-check i-button-null pad-left"></i>
		<div class="div-form-control">
		</div>
		<i class="icofont-simple-up i-button pad-right"></i>
	</div>
</div>
<!-- Body -->
<div class="card-body body-vales-colaborador">
	{% for cat in category_n3_out %}
	<div class="card-body-item">
		<div class="input-group">
			<div class="input-group-addon addon-my-color">
				<i class="i-button-null">{{ forloop.counter|stringformat:"02d" }}</i>
			</div>
		<div class="div-flex div-form-control">
			<div class="tamanho-70 text-left">
				<span>{{ cat.category }}</span>
			</div>
			<div class="tamanho-30 text-right color-red">
				<span>R$ {{ cat.value }}</span>
			</div>
		</div>
		<div class="input-group-addon addon-my-color">
			<i class="icofont-eye-alt i-button"
			title=""></i>
		</div>
	</div>
</div>
{% endfor %}
</div>
<!-- Footer -->
<div class="card-footer">
	<div class="div-flex">
		<div class="div-form-control div-flex">
			<div class="tamanho-80 text-left">
				<span class="font-menor"></span>
			</div>
			<div class="tamanho-20 text-right">
				<span class="font-menor"></span>
			</div>
		</div>
	</div>
</div>

transactions/templates/transactions/card_registries_period.html
<!-- Header -->
<div class="card-header">
	<div class="div-flex">
		<i class="icofont-plus i-button pad-left"
			onclick="openMyModal(event); return false;"
			data-title="ADICIONA TRANSAÇÃO"
			data-action="add_registry"
			data-button-save-label="SALVAR"
			title="Adiciona Transação"></i>
		<div class="div-form-control">
			<span>TRANSAÇÕES PAGAS</span>
		</div>
		<i class="icofont-simple-up i-button pad-right js-toggle-registries-period"></i>
	</div>
</div>
<!-- Body -->
<div class="card-body body-vales-colaborador js-body-registries-period">
	{% for method in methods %}
	<div class="card-body-item">
		<div class="input-group">
			<div class="input-group-addon addon-my-color">
				<i class="i-button-null">{{ forloop.counter|stringformat:"02d" }}</i>
			</div>
		<div class="div-flex div-form-control">
			<div class="tamanho-20 text-center">
				<span>{{ method.payment.date|date:"d/m/y" }}</span>
			</div>
			<div class="tamanho-60 text-left">
				<span title="{{ method.payment.registry.id }}">
					{{ method.payment.registry.companies.name }}
				</span>
			</div>
			{% if method.payment.registry.in_out %}
			<div class="tamanho-20 text-right color-green">
				<span>R$ {{ method.payment.registry.value }}</span>
			</div>
			{% else %}
			<div class="tamanho-20 text-right color-red">
				<span>R$ {{ method.payment.registry.value }}</span>
			</div>
			{% endif %}
		</div>
		<div class="input-group-addon addon-my-color addon-first">
			<i class="icofont-trash i-button"
				onclick="openMyModal(event); return false;"
				data-title=""
				data-action=""
				data-button-save-label=""
				data-confirma=""
				data-idconfirma=""
				title=""></i>
		</div>
		<div class="input-group-addon addon-my-color">
			<i class="icofont-eye-alt i-button js-mostra-itens"
				data-registry-id="{{ method.payment.registry.id }}"
				title="Consuta Itens"></i>
		</div>
	</div>
</div>
{% endfor %}
</div>
<!-- Footer -->
<div class="card-footer js-footer-registries-period">
	<div class="div-flex">
		<div class="div-form-control div-flex">
			<div class="tamanho-80 text-left">
				<span class="font-menor"></span>
			</div>
			<div class="tamanho-20 text-right">
				<span class="font-menor"></span>
			</div>
		</div>
	</div>
</div>

transactions/templates/transactions/card_registries_unpaid.html
<!-- Header -->
<div class="card-header">
	<div class="div-flex">
		<i class="icofont-plus i-button pad-left"
			onclick="openMyModal(event); return false;"
			data-title="ADICIONA TRANSAÇÃO"
			data-action="add_registry"
			data-button-save-label="SALVAR"
			title="Adiciona Transação"></i>
		<div class="div-form-control">
			<span>TRANSAÇÕES A PAGAR</span>
		</div>
		<i class="icofont-simple-up i-button pad-right js-toggle-registries-unpaid"></i>
	</div>
</div>
<!-- Body -->
<div class="card-body body-vales-colaborador js-body-registries-unpaid">
	{% for unpaid in unpaids %}
	<div class="card-body-item">
		<div class="input-group">
			<div class="input-group-addon addon-my-color">
				<i class="i-button-null">{{ forloop.counter|stringformat:"02d" }}</i>
			</div>
		<div class="div-flex div-form-control">
			<div class="tamanho-20 text-center">
				<span>{{ unpaid.date|date:"d/m/y" }}</span>
			</div>
			<div class="tamanho-60 text-left">
				<span title="{{ unpaid.id }}">
					{{ unpaid.companies.name }}
				</span>
			</div>
			{% if unpayd.in_out %}
			<div class="tamanho-20 text-right color-green">
				<span>R$ {{ unpaid.value }}</span>
			</div>
			{% else %}
			<div class="tamanho-20 text-right color-red">
				<span>R$ {{ unpaid.value }}</span>
			</div>
			{% endif %}
		</div>
		<div class="input-group-addon addon-my-color addon-first">
			<i class="icofont-money-bag i-button"
				onclick="openMyModal(event); return false;"
				data-title="ADICIONA PAGAMENTO"
				data-action="add_payment"
				data-button-save-label="SALVAR"
				data-id-selected="{{ unpaid.id }}"
				title="Adiciona Pagamento"></i>
		</div>
		<div class="input-group-addon addon-my-color">
			<i class="icofont-eye-alt i-button js-mostra-itens" data-registry-id="{{ unpaid.id }}"
			title="Consuta Itens"></i>
		</div>
	</div>
</div>
{% endfor %}
</div>
<!-- Footer -->
<div class="card-footer js-footer-registries-unpaid">
	<div class="div-flex">
		<div class="div-form-control div-flex">
			<div class="tamanho-80 text-left">
				<span class="font-menor"></span>
			</div>
			<div class="tamanho-20 text-right">
				<span class="font-menor"></span>
			</div>
		</div>
	</div>
</div>

transactions/templates/transactions/modal_form_category.html
<form class="row g-3" method="post" action="{% url 'add_category' %}">
	{% csrf_token %}
	<div class="col-md-12">
		<div class="form-group">
			<div class="input-group-addon addon-top">
				<label for="id_description" class="form-label">DESCRIÇÃO</label>
			</div>
			<div>
				{{ form.description }}
				{{ form.description.errors }}
			</div>
		</div>
	</div>
</form>

transactions/templates/transactions/modal_form_company.html
<form class="row g-3" method="post" action="{% url 'add_company' %}">
	{% csrf_token %}
	<div class="col-md-12">
		<div class="form-group">
			<div class="input-group-addon addon-top">
				<label for="id_name" class="form-label">FAVORECIDO</label>
			</div>
			<div>
				{{ form.name }}
				{{ form.name.errors }}
			</div>
		</div>
	</div>
</form>

transactions/templates/transactions/modal_form_payment.html
<form class="row g-3" method="POST" action="add_payment">
	{% csrf_token %}
	<div class="col-md-9">
		<div class="form-group">
			<div class="input-group-addon addon-top">
				<label for="id_registry" class="form-label">REGISTRO</label>
			</div>
			<div>
				<input type="text" value="{{ registry }}" class="form-control text-center" readonly id="id_registry">
			</div>
		</div>
	</div>
	<div class="col-md-3">
		<div class="form-group">
			<div class="input-group-addon addon-top">
				<label for="id_date" class="form-label">DATA</label>
			</div>
			<div>
				{{ form.date }}
				{{ form.date.errors }}
			</div>
		</div>
	</div>
    <input type="hidden" name="registry_id" value="{{ registry.id }}">
</form>

transactions/templates/transactions/modal_form_registry.html
<form class="row g-3" method="POST" action="add_registry">
	{% csrf_token %}
	<div class="col-md-3">
        <div class="form-group">
            <div class="input-group-addon addon-top">
                <label for="id_date" class="form-label">DATA</label>
            </div>
            <div>
                {{ form.date }}
                {{ form.date.errors }}
            </div>
        </div>
    </div>
	<div class="col-md-3">
        <div class="form-group">
            <div class="input-group-addon addon-top">
                <label for="id_value" class="form-label">VALOR</label>
            </div>
            <div>
                {{ form.value }}
                {{ form.value.errors }}
            </div>
        </div>
    </div>
	<div class="col-md-3">
        <div class="form-group">
            <div class="input-group-addon addon-top">
                <label for="id_in_out" class="form-label">TIPO</label>
            </div>
            <div>
                {{ form.in_out }}
                {{ form.in_out.errors }}
            </div>
        </div>
    </div>
	<div class="col-md-3">
        <div class="form-group">
            <div class="input-group-addon addon-top">
                <label for="id_ordering" class="form-label">ORDEM</label>
            </div>
            <div>
                {{ form.ordering }}
                {{ form.ordering.errors }}
            </div>
        </div>
    </div>
	<div class="col-md-6">
        <div class="form-group">
            <div class="input-group-addon addon-top">
                <label for="id_companies" class="form-label">EMPRESA</label>
            </div>
            <div>
                {{ form.companies }}
                {{ form.companies.errors }}
            </div>
        </div>
    </div>
	<div class="col-md-6">
         <div class="form-group">
            <div class="input-group-addon addon-top">
                <label for="id_category_n1" class="form-label">CATEGORIA</label>
            </div>
            <div>
                {{ form.category_n1 }}
                {{ form.caterory_n1.errors }}
            </div>
        </div>
    </div>
	<div class="col-md-6">
         <div class="form-group">
            <div class="input-group-addon addon-top">
                <label for="id_category_n2" class="form-label">SUB-CATEGORIA</label>
            </div>
            <div>
                {{ form.category_n2 }}
                {{ form.category_n2.errors }}
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <div class="input-group-addon addon-top">
                <label for="id_category_n3" class="form-label">SEGUIMENTO</label>
            </div>
            <div>
                {{ form.category_n3 }}
                {{ form.category_n3.errors }}
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <div class="input-group-addon addon-top">
                <label for="id_obs" class="form-label">OBSERVAÇÕES:</label>
            </div>
            <div>
                {{ form.obs }}
                {{ form.obs.errors }}
            </div>
        </div>
    </div>
</form>