financeiro/urls.py
from django.contrib import admin
from django.urls import path, include
from website import urls as website_urls
from transactions import urls as transactions_urls
from monetary import urls as monetary_urls


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(website_urls)),
    path("transactions/", include(transactions_urls)),
    path("monetary/", include(monetary_urls)),
]

monetary/urls.py
from django.urls import path
from monetary.views import (
    add_transfer,
    index_monetary,
)


urlpatterns = [
    path(
        "add_transfer",
        add_transfer,
        name="add_transfer",
    ),
    path(
        "index_monetary",
        index_monetary,
        name="index_monetary",
    ),
]

website/urls.py
from django.urls import path
from website.views import (index_website,)


urlpatterns = [
    path("", index_website, name="index_website",),

]

monetary/models.py
""" Define the structure of stored data """

from django.db import models


class Accounts(models.Model):
    """
        Model Accounts
    Attributes:
        name:
        description:

    """

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20, unique=True)
    description = models.TextField(max_length=240)
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    class Meta:  # pylint: disable=R0903
        """Sorted by name field"""

        db_table = "monetary_accounts"
        ordering = ("name",)

    def save(self, *args, **kwargs):
        """Save datas in uppercase"""
        self.name = self.name.upper()
        self.description = self.description.upper()

        super().save(*args, **kwargs)

    def __str__(self):
        """String for representing the ModelName object"""
        return str(self.name)

    objects = models.Manager()


class Transfers(models.Model):
    id = models.AutoField(primary_key=True)
    out_account = models.ForeignKey(
        Accounts, on_delete=models.CASCADE, related_name="outgoing_transfers"
    )
    in_account = models.ForeignKey(
        Accounts, on_delete=models.CASCADE, related_name="incoming_transfers"
    )
    value = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()

    class Meta:
        db_table = "monetary_transfers"
        ordering = ("date", "out_account", "in_account")

    def save(self, *args, **kwargs):
        super().save(self, *args, **kwargs)

    def __str__(self):
        return str(f"{self.out_account} - {self.in_account} - R$ {self.value}")

    objects = models.Manager()

monetary/forms.py
import datetime
from django import forms
from monetary import models


class DateInput(forms.DateInput):
    input_type = "date"


class TransferForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["date"].initial = datetime.date.today()

    class Meta:
        accounts = models.Accounts.objects.all()
        model = models.Transfers
        fields = "__all__"
        widgets = {
            "out_account": forms.Select(
                attrs={"class": "form-control"},
                choices=[(item.id, item.name) for item in accounts],
            ),
            "in_account": forms.Select(
                attrs={"class": "form-control"},
                choices=[(item.id, item.name) for item in accounts],
            ),
            "value": forms.NumberInput(attrs={"class": "form-control"}),
            "date": DateInput(
                format="%Y-%m-%d", attrs={"class": "form-control text-center"}
            ),
        }

monetary/views.py
from django.shortcuts import render
from monetary import facade as mf

# Create your views here.


def index_monetary(request):
    context = {"nada": "nada"}
    return render(request, "monetary/index_monetary.html", context)


def add_transfer(request):
    if request.method == "GET":
        data = mf.form_transfers(request)
    else:
        mf.save_transfer(request)
        data = mf.create_transfer_data_message(request)
    return data

monetary/templates/monetary/index_monetary.html
{% extends "website/base.html" %}
{% load static %}
{% block container %}
<main class="section-grid">
    <section class="grid-column">
        <div class="left-menu">
            <i class="icofont-exchange left-menu-item"
               onclick="openMyModal(event); return false;"
               data-title="TRANSFERÊNCIA ENTRE CONTAS"
               data-action="add_transfer"
               data-button-save-label="SALVAR"
               title="Adiciona Transferência"></i>
        </div>
    </section>
    <section class="grid-column">
        <div class="card card...">
        </div>
    </section>
    <section class="grid-column">
        <div class="card card...">
        </div>
    </section>
    <section class="grid-column">
        <div class="card card-registries">
            {% include "transactions/card_registries_period.html" %}
        </div>
    </section>
</main>
{% endblock container %}

monetary/templates/monetary/modal_form_transfer.html
<form class="row g-3" method="post" action="{% url 'add_transfer' %}">
	{% csrf_token %}
	<div class="col-md-3">
		<div class="form-group">
			<div class="input-group-addon addon-top">
				<label for="id_date" class="form-label">DATA</label>
			</div>
			<div>
				{{ form.date }}
				{{ form.date.errors }}
			</div>
		</div>
	</div>

	<div class="col-md-3">
		<div class="form-group">
			<div class="input-group-addon addon-top">
				<label for="id_out_account" class="form-label">CONTA SAÍDA</label>
			</div>
			<div>
				{{ form.out_account }}
				{{ form.out_account.errors }}
			</div>
		</div>
	</div>
	<div class="col-md-3">
		<div class="form-group">
			<div class="input-group-addon addon-top">
				<label for="id_in_account" class="form-label">CONTA ENTRADA</label>
			</div>
			<div>
				{{ form.in_account }}
				{{ form.in_account.errors }}
			</div>
		</div>
	</div>
	<div class="col-md-3">
		<div class="form-group">
			<div class="input-group-addon addon-top">
				<label for="id_value" class="form-label">VALOR</label>
			</div>
			<div>
				{{ form.value }}
				{{ form.value.errors }}
			</div>
		</div>
	</div>

</form>